name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at 00:00 UTC every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3  # Updated to use Node.js 20

      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: generate_snk
        with:
          github_user_name: aishwarya-wagh
          svg_out_path: github-contribution-grid-snake.svg  # Corrected input parameter name

      - name: Verify SVG file exists
        run: ls -la

      - name: Move SVG to assets
        run: |
          mkdir -p assets
          mv github-contribution-grid-snake.svg assets/

      - name: Verify SVG moved
        run: ls -la assets

      - name: Commit and push the SVG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generate snake animation"
          file_pattern: "assets/github-contribution-grid-snake.svg"
