name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at 00:00 UTC every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: generate-snake
        with:
          github_user_name: aishwarya-wagh
          gif_out_path: dist/github-snake.gif
          svg_out_path: aishwarya-wagh/assets/github-snake.svg

      - name: Commit and push the SVG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generate snake animation"
          file_pattern: "aishwarya-wagh/assets/github-snake.svg"
          branch: main
